let myLibrary = [
  {
    bookName: "Atomic Habits",
    author: "James Clear",
    bookPublished: "October 16, 2018",
    language: "English",
    publisher: "Penguin Publishing Group",
    pageCount: 320,
    shortInfo: "An Easy & Proven Way to Build Good Habits & Break Bad Ones",
    isRead: true,
  },
  {
    bookName: "Learning How to Learn",
    author: "Barbara Oakley, PhD",
    bookPublished: "August 7, 2018",
    language: "English",
    publisher: "Penguin Publishing Group",
    pageCount: 256,
    shortInfo:
      "How to Succeed in School Without Spending All Your Time Studying; A Guide for Kids and Teens",
    isRead: false,
  },
  {
    bookName: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    bookPublished: "April 10, 1925",
    language: "English",
    publisher: "Charles Scribner's Sons",
    pageCount: 180,
    shortInfo:
      "A classic novel exploring the decadence and moral decline of the Jazz Age.",
    isRead: true,
  },
  {
    bookName: "To Kill a Mockingbird",
    author: "Harper Lee",
    bookPublished: "July 11, 1960",
    language: "English",
    publisher: "J. B. Lippincott & Co.",
    pageCount: 324,
    shortInfo:
      "A Pulitzer Prize-winning novel that addresses racial injustice and moral growth in the American South.",
    isRead: false,
  },
  {
    bookName: "1984",
    author: "George Orwell",
    bookPublished: "June 8, 1949",
    language: "English",
    publisher: "Secker & Warburg",
    pageCount: 328,
    shortInfo:
      "A dystopian novel portraying a totalitarian society and the consequences of government overreach.",
    isRead: true,
  },
  {
    bookName: "Pride and Prejudice",
    author: "Jane Austen",
    bookPublished: "January 28, 1813",
    language: "English",
    publisher: "T. Egerton, Whitehall",
    pageCount: 432,
    shortInfo:
      "A romantic novel following the lives of the Bennet sisters and their pursuit of love and happiness.",
    isRead: false,
  },
  {
    bookName: "The Lord of the Rings",
    author: "J.R.R. Tolkien",
    bookPublished: "July 29, 1954",
    language: "English",
    publisher: "Allen & Unwin",
    pageCount: 1178,
    shortInfo:
      "An epic fantasy trilogy chronicling the quest to destroy the One Ring and defeat the dark lord Sauron.",
    isRead: true,
  },
  {
    bookName: "To the Lighthouse",
    author: "Virginia Woolf",
    bookPublished: "May 5, 1927",
    language: "English",
    publisher: "Hogarth Press",
    pageCount: 209,
    shortInfo:
      "A novel exploring the complexities of human relationships and the passage of time through the Ramsay family.",
    isRead: false,
  },
  {
    bookName: "One Hundred Years of Solitude",
    author: "Gabriel García Márquez",
    bookPublished: "May 30, 1967",
    language: "Spanish",
    publisher: "Harper & Row",
    pageCount: 417,
    shortInfo:
      "A magical realist novel tracing the multi-generational story of the Buendía family in the fictional town of Macondo.",
    isRead: true,
  },
  {
    bookName: "Brave New World",
    author: "Aldous Huxley",
    bookPublished: "February 2, 1932",
    language: "English",
    publisher: "Chatto & Windus",
    pageCount: 311,
    shortInfo:
      "A dystopian novel portraying a society organized on the principles of mass production, pleasure, and conformity.",
    isRead: false,
  },
  {
    bookName: "The Catcher in the Rye",
    author: "J.D. Salinger",
    bookPublished: "July 16, 1951",
    language: "English",
    publisher: "Little, Brown and Company",
    pageCount: 277,
    shortInfo:
      "A coming-of-age novel following Holden Caulfield's journey through adolescence and alienation.",
    isRead: true,
  },
  {
    bookName: "Harry Potter and the Sorcerer's Stone",
    author: "J.K. Rowling",
    bookPublished: "June 26, 1997",
    language: "English",
    publisher: "Bloomsbury",
    pageCount: 223,
    shortInfo:
      "The first book in the fantasy series about a young wizard, Harry Potter, and his adventures at Hogwarts School of Witchcraft and Wizardry.",
    isRead: false,
  },
  {
    bookName: "Crime and Punishment",
    author: "Fyodor Dostoevsky",
    bookPublished: "January 1866",
    language: "Russian",
    publisher: "The Russia Messenger",
    pageCount: 671,
    shortInfo:
      "A psychological novel delving into the inner turmoil of a young man, Raskolnikov, after committing a murder.",
    isRead: true,
  },
];
